-- Encerra os dois baldes que a migration 20260812140000 deixou anotados.
--
-- O QUE A AUDITORIA DE 20/08/2026 APUROU
-- A migration de 12/08 fechou o isolamento de 'process-attachments' e registrou,
-- nas suas linhas 119-133, que 'legal_documents' e 'legal-attachments' tinham o
-- mesmo defeito — política "FOR ALL TO authenticated USING (bucket_id = ...)",
-- sem filtro de workspace. Não foram corrigidos ali porque não se sabia se
-- estavam em uso. Agora se sabe:
--
--   balde                objetos
--   -------------------  -------
--   process-attachments       33   <- o único em uso
--   workspace-branding         2
--   Escritorio                 1   <- ver nota ao final
--   legal_documents            0
--   legal-attachments          0
--
-- Os dois baldes defeituosos NUNCA receberam um arquivo. A política era errada
-- e a consequência foi nenhuma: não houve exposição de dado de cliente.
--
-- 'legal_documents' era o destino da aba "Anexos" (src/pages/Processos.tsx).
-- O código foi repontado para 'process-attachments' ANTES desta migration, com
-- caminho <user_id>/<uuid>-<nome>, porque a política pa_storage_insert exige
-- que a primeira pasta seja o auth.uid(). A ORDEM IMPORTA: aplicar isto com o
-- código antigo no ar transformaria um caminho morto e inofensivo em erro
-- visível para o testador.

-- ---------------------------------------------------------------------------
-- 1) As políticas defeituosas.
-- ---------------------------------------------------------------------------
drop policy if exists "authenticated_manage_legal_documents" on storage.objects;
drop policy if exists "Authenticated users can select legal-attachments" on storage.objects;
drop policy if exists "Authenticated users can upload legal-attachments" on storage.objects;
drop policy if exists "Authenticated users can delete legal-attachments" on storage.objects;

-- ---------------------------------------------------------------------------
-- 2) Os baldes NÃO são apagados aqui — e não por escolha nossa.
--
--    A primeira versão desta migration apagava as duas linhas de
--    storage.buckets. O banco recusou:
--
--      ERROR: 42501: Direct deletion from storage tables is not allowed.
--             Use the Storage API instead.
--      HINT:  This prevents accidental data loss from orphaned objects.
--      CONTEXT: PL/pgSQL function storage.protect_delete()
--
--    A Supabase passou a impor no banco a mesma regra que este projeto já
--    tinha aprendido em 12/08 e escrito em limpa_orfaos.py: apagar a linha em
--    storage.objects remove o REGISTRO e não o ARQUIVO. Quem apaga por SQL
--    troca um resíduo rastreável por um invisível. O gatilho existe para
--    impedir exatamente isso.
--
--    Como apagar os dois baldes vazios, então: pelo painel da Supabase,
--    Storage -> selecionar o balde -> Delete bucket. Passa pela Storage API,
--    que remove registro e conteúdo. Sem chave de serviço, porque o painel já
--    está autenticado.
--
--    Conferir antes que continuam vazios:
--
--      select bucket_id, count(*)
--        from storage.objects
--       where bucket_id in ('legal_documents', 'legal-attachments')
--       group by bucket_id;
--
--    Zero linhas no resultado = os dois estão vazios e podem ser apagados.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 3) O balde 'Escritorio' NÃO é tocado aqui, de propósito.
--
--    Não consta de nenhuma migration do repositório: foi criado à mão em
--    15/06, mesma data do 'workspace-branding', e guarda 1 arquivo de 904 kB —
--    provavelmente um logo.
--
--    Não tem política NENHUMA. Com RLS ativo em storage.objects e nenhuma
--    política casando, nenhum usuário autenticado lê, grava ou apaga ali: só a
--    service_role alcança. Não é exposição.
--
--    Mas é dado que nenhuma eliminação orientada por processo atinge — a mesma
--    natureza dos órfãos, para efeito da cláusula 10 do DPA.
--
--    IDENTIFICAR o arquivo é uma consulta comum: o SQL Editor roda acima do
--    RLS, então enxerga o que o aplicativo não enxerga.
--
--      select o.name, o.created_at::date, o.owner,
--             pg_size_pretty((o.metadata->>'size')::bigint) as tamanho,
--             o.metadata->>'mimetype' as tipo
--        from storage.objects o
--       where o.bucket_id = 'Escritorio';
--
--    APAGAR, esse sim, exige a Storage API — painel ou chave de serviço, pela
--    mesma razão do item 2.
-- ---------------------------------------------------------------------------
